# Generated by Django 4.0.4 on 2022-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('moves', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
